GIK-38 CRUD operations for students requests
getinfokhpi/getinfo pull request #14
Opened 2023-11-17 21:05 UTC by BroodCaster

2023-11-17 21:55 UTC, HappyMary16 requested changes

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/directions.ts
Чи перевіряли всі запити які опрацьовуються в цьому вайлі після змін, які внесли?

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/directions.ts
> +          // subDirections: {
Чому закоментували цей фрагмент?

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/directions.ts
> +          requests: true
Впевнені що запити потрібно включати в категарію? Він хоч і має бути повʼязаний з категорією, але це 2 різні сутності, які мають діставатися окремими запитами

2023-11-17 21:55 UTC, HappyMary16 commented on prisma/schema.prisma
> +  requests        Request[]
Чи точно тут потрібні запити? Запит має бути окремою сутністю хоч в ньому і має бути посилання на категорію, для якої він створений

2023-11-17 21:55 UTC, HappyMary16 commented on prisma/schema.prisma
> +  directions      Directions @relation(fields: [directionId], references: [id])
Чому видалили onDelete: Cascade?
Він тут був не просто так

2023-11-17 21:55 UTC, HappyMary16 commented on prisma/schema.prisma
> +  questionId      Int       @unique
Підозрюю це поле має називатися requestId

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/direction/get/[id].ts
> +        requests: true
напевно це зайве тут

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/directions.ts
> +        const { id, name, description, subDirectionName, additionalInfo, exampleLink, downloadFile, textField, professor } = req.body;
в категорії в нас може бути багато підкатегорій, у вас не можливо додати  багато підкатегорій

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/directions.ts
Також ви можете винести опрацювання всіх запитів в окремі методи і викликати їх в методі handler
Тоді на цей код буде набагато приємніше дивитися

2023-11-17 21:55 UTC, HappyMary16 commented on src/lib/prisma.ts
> +import { PrismaClient } from "@prisma/client";
В інших файлах наче використовуються одинарні лапки, думаю і тут можна залишити їх

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/requests.ts
> +      }else if(req.method === "GET"){
Будь ласка, підтримуйтеся одного стилю написання коду. Чому тут відступів біля операторів if else нема, а вище є? Додавайте відступи, з ними ж читати ваш код зрозуміліше.

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/requests/create.ts
Чим це створення запиту відрізняється від того, яке реалізоване в файлі requests? Крім юрл звичайно ж
Тут ще й виходить гірша
localhost:3000/api/requests/create
Навіщо писати в БРЛ дію, якщо вона зрозуміла з методу (POST) який ми виконуємо

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/requests/delete/[id].ts
Такий же коментар як і до create

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/requests/get/[id].ts
В файлі requests ви реалізували і діставання за ід, цей варіант чимось відрізняється?

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/requests/get/direction/[id].ts
теж питання що і до файлі з опрацюванням запитів requests

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/requests/update/[id].ts
теж питання що і до файлі з опрацюванням запитів requests

І до речі в запиті має могти оновлюватися тільки статус, інші поля оновлювати не можна

2023-11-17 21:55 UTC, HappyMary16 commented on src/pages/api/upload.ts
Можете розповісти як це працює і як мені завантажити файл?
Бо я отримую у відповідь таке повідомлення
{
    "success": false,
    "message": "Error uploading file"
}

2023-11-17 21:57 UTC, BroodCaster commented on prisma/schema.prisma
> +  directions      Directions @relation(fields: [directionId], references: [id])
вибачте, не помітив в конфліктах мерджу

2023-11-20 16:59 UTC, BroodCaster commented
@HappyMary16 Перегляньте будь ласка зміни. Щодо api upload воно не зберігало, я його переробив і тепер всі загружені файли зберігаються в папці public/uploads

2023-11-22 10:12 UTC, HappyMary16 approved these changes

2023-11-23 09:48 UTC, merged