GIK-50 Added authorization to all endpoints, added data validation
getinfokhpi/getinfo pull request #28
Opened 2024-03-14 19:42 UTC by BroodCaster

2024-03-16 13:49 UTC, ArCheeq commented
@BroodCaster, було б добре щоб в нас була одна структура для кожного ендпоінта, що я маю на увазі:

Під кожен ендпоінт 1 папка (messages/directions/requests) -> у цій папці знаходяться 2 файла (index.ts та [id].ts) -> у файлі index.ts знаходяться обробники для POST та GET (створення/отримання усіх данних), а у файлі [id].ts знаходяться обробники для PUT/DELETE/GET (оновлення/видалення/редагування 1 елемента за id у query.id). Як для прикладу ендпоінт messages він реалізований за даним принципом.

2024-03-16 14:38 UTC, ArCheeq commented
@BroodCaster 
1) Перевір чи у всіх файлах ти додав валідацію.
2) Простав перевірку ролей у ендпоінтах, лише перевірки за session - недостатньо.

Ось необхідна перевірка ролей для кожного ендпоінта:

- File upload endpoint
Доступ до завантаження документів має бути у будь-якого авторизованого користувача.

- Directions
Get All - доступ у будь-якого авторизованого юзера
Post - тільки адмін
Put - тільки admin
Delete - тільки адмін
Get by id: - доступ у будь-якого авторизованого юзера

- Requests
Get All - студент може отримати лише власні заявки, відповідальний викладач може отримати тільки заявки у яких поле professor === user.email, адмін може отримати усі завки
Post - тільки студенти
Patch - будь-який авторизований користувач (Вони можуть змінювати тільки статус заявки - інші поля НІ)
Delete - не потрібен нам.
Get by id: - так само як і у Get All.

- Messages
Post:  будь-який авторизований користувач
Get by Request id: студент може отримати повідомлення лише з власних заявок, викладач тільки з заявок у яких поле professor === user.email, адмін - усі.

- Faq
Get All: будь-який користувач, навіть і не авторизований
Get by id: будь-який користувач, навіть і не авторизований
POST: тільки адмін
Delete: тільки адмін
Put: тільки адмін

2024-03-16 14:41 UTC, ArCheeq requested changes
Дякую, що додав валідацію. Виправи будь-ласка зауваження.

2024-03-16 14:41 UTC, ArCheeq commented on src/pages/api/faq/index.ts
> +    if (session) {
Не треба повністю обгортати усі ендпоінти у файлі: в даному випадку GET ALL запит має працювати і для **НЕ АВТОРИЗОВАНОГО** користувача, **всі інші** мають працювати для користувача з **РОЛЛЮ admin**

2024-03-16 14:41 UTC, ArCheeq commented on src/pages/api/faq/index.ts
> +    if (session) {
Ось приклад:
```
const session = await getServerSession(req, res, authConfig)
    if (req.method === "POST") {
        if (!session?.roles.includes(roles.ROLE_SUPPORT_ADMIN)) {
            return res.status(405).json({ error: "You do not have permission to perform this operation" })
        }
        ...
    }
```

2024-03-16 14:41 UTC, ArCheeq commented on src/pages/api/faq/index.ts
> +import authOptions from "../auth/[...nextauth]"
Я так розумію, що ти не тестив це, бо конфіг в нас знаходиться ось тут:

```import { authConfig } from "@/configs/auth";```

Зміни імпорти у всіх файлах, будь-ласка

2024-03-16 14:41 UTC, ArCheeq commented on src/pages/api/faq/index.ts
> +                if (!value.question || !value.answer || !value.questionType) {
Може чого не розумію, але навіщо тобі цей if, коли на пару строк вище ти запускаєш валідацію, і перевіряєш чи є помилки ?

2024-04-03 11:47 UTC, HappyMary16 approved these changes

2024-04-05 13:54 UTC, ArCheeq approved these changes
LGTM

2024-04-05 13:55 UTC, merged